apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: confirmation-reports-be-external
  namespace: outpost-demo
spec:
  data:
  - secretKey: AppSecrets.json
    remoteRef:
      key: confirmation-reports-be/app
  - secretKey: AppSecrets.Db.json
    remoteRef:
      key: confirmation-reports-be/db
  - secretKey: AppSecrets.MigrationData.Db.json
    remoteRef:
      key: confirmation-reports-be/db
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: a207804-cn-aws
  target:
    name: confirmation-reports-be-secrets
    creationPolicy: Owner