apiVersion: v1
kind: Secret
metadata:
  name: confirmation-reports-be-secrets
  namespace: outpost-demo
  ownerReferences:
  - apiVersion: external-secrets.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: confirmation-reports-be-external
    uid: abcdefgh-1234-5678-9012-abcdefghijklmno